name: 'create dmg'
description: 'Create dmg on macOS by actions'
author: 'L-Super'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  src_dir:
    description: 'source dir'
    default: 'src_dir'
  dmg_name:
    description: 'dmg name'
    default: 'dmg_name'

runs:
  using: node20
  main: dist/index.js
